---
- name: Add Docker repo (RHEL)
  get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: Install Docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: yes

# tasks file for roles/docker
